### ISSUE TITLE
iD Support

### ISSUE THREAD

**Issue by sethfitz** [developmentseed/macrocosm#11]
macrocosm should work with a minimally-modified version of iD.

**Comment by sethfitz** [comment]
FYI, I'm working on this [here](https://github.com/americanredcross/macrocosm) and will submit PRs once it a) works and b) I'm happy with how it's working.

(This issue exists to avoid duplicating effort.)

**Comment by sethfitz** [comment]
@olafveerman how would you like me to submit PRs? The changes ended up being a bit more involved than I'd originally hoped (and because they were, I kept going).

The upshot is that I have edits working end-to-end in iD.

They're almost working in JOSM for small areas; large `map` queries are too slow to work properly and the changeset response causes errors (in JOSM).

**Comment by olafveerman** [comment]
Thanks @mojodna, this is great!
Ideally we'd review PR's with more isolated features, but if you issue a PR against `develop`, we'll take it from there.

cc @dereklieu @danielfdsilva @kamicut

**Comment by sethfitz** [comment]
Cool, yeah, I'd rather submit PRs with more isolated features too ;-) We'll get there!
